/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.Duration;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import javax.swing.text.DateFormatter;

/**
 *
 * @author juane
 */
public class mainPanel extends javax.swing.JPanel {

	/**
	 * Creates new form mainFrame
	 */
	public mainPanel() {
		initComponents();
		buttonGroup_choose.add(rad_count);
		buttonGroup_choose.add(rad_clock);
		buttonGroup_options.add(rad_pow);
		buttonGroup_options.add(rad_rest);
		buttonGroup_options.add(rad_sleep);
                buttonGroup_options.add(rad_lock);
                jSpinner_count_h.setValue(1);
	}

    public JSpinner getjSpinner_count_h() {
        return jSpinner_count_h;
    }

    public JSpinner getjSpinner_count_m() {
        return jSpinner_count_m;
    }

    public JSpinner getjSpinner_count_s() {
        return jSpinner_count_s;
    }

    public JSpinner getjSpinner_date() {
        return jSpinner_date;
    }

    public JSpinner getjSpinner_time() {
        return jSpinner_time;
    }

        
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup_choose = new javax.swing.ButtonGroup();
        buttonGroup_options = new javax.swing.ButtonGroup();
        panel_title = new javax.swing.JPanel();
        label_title = new javax.swing.JLabel();
        panel_left = new javax.swing.JPanel();
        panel_fast = new javax.swing.JPanel();
        title_fast = new javax.swing.JLabel();
        fast_10 = new javax.swing.JLabel();
        fast_20 = new javax.swing.JLabel();
        fast_30 = new javax.swing.JLabel();
        fast_1 = new javax.swing.JLabel();
        fast_2 = new javax.swing.JLabel();
        fast_3 = new javax.swing.JLabel();
        panel_center = new javax.swing.JPanel();
        panel_choose = new javax.swing.JPanel();
        rad_count = new javax.swing.JRadioButton();
        rad_clock = new javax.swing.JRadioButton();
        panel_timer = new javax.swing.JPanel();
        panel_timer_countdown = new javax.swing.JPanel();
        jSpinner_count_h = new javax.swing.JSpinner();
        jSpinner_count_m = new javax.swing.JSpinner();
        jSpinner_count_s = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        panel_timer_clock = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Date now = new Date();
        SpinnerDateModel model=new SpinnerDateModel(now, null, null, Calendar.DAY_OF_MONTH);
        jSpinner_date = new javax.swing.JSpinner(model);
        jSpinner_time = new javax.swing.JSpinner();
        panel_options = new javax.swing.JPanel();
        rad_pow = new javax.swing.JRadioButton();
        rad_rest = new javax.swing.JRadioButton();
        rad_sleep = new javax.swing.JRadioButton();
        rad_lock = new javax.swing.JRadioButton();
        button_run = new javax.swing.JButton();
        button_cancel = new javax.swing.JButton();
        panel_bottom = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        panel_title.setLayout(new java.awt.BorderLayout());

        label_title.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        label_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_title.setText("POWER MANAGEMENT");
        panel_title.add(label_title, java.awt.BorderLayout.CENTER);

        add(panel_title, java.awt.BorderLayout.NORTH);

        panel_fast.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        title_fast.setBackground(new java.awt.Color(255, 0, 6));
        title_fast.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title_fast.setText("Fast Power Off");

        fast_10.setText("In 10 minutes");

        fast_20.setText("In 20 minutes");

        fast_30.setText("In 30 minutes");

        fast_1.setText("In 1 hour");

        fast_2.setText("In 2 hours");

        fast_3.setText("In 3 hours");

        javax.swing.GroupLayout panel_fastLayout = new javax.swing.GroupLayout(panel_fast);
        panel_fast.setLayout(panel_fastLayout);
        panel_fastLayout.setHorizontalGroup(
            panel_fastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(title_fast, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel_fastLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_fastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fast_10)
                    .addComponent(fast_20)
                    .addComponent(fast_30)
                    .addComponent(fast_1)
                    .addComponent(fast_2)
                    .addComponent(fast_3))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        panel_fastLayout.setVerticalGroup(
            panel_fastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_fastLayout.createSequentialGroup()
                .addComponent(title_fast, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fast_10)
                .addGap(18, 18, 18)
                .addComponent(fast_20)
                .addGap(18, 18, 18)
                .addComponent(fast_30)
                .addGap(18, 18, 18)
                .addComponent(fast_1)
                .addGap(18, 18, 18)
                .addComponent(fast_2)
                .addGap(18, 18, 18)
                .addComponent(fast_3)
                .addGap(0, 19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panel_leftLayout = new javax.swing.GroupLayout(panel_left);
        panel_left.setLayout(panel_leftLayout);
        panel_leftLayout.setHorizontalGroup(
            panel_leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_leftLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_fast, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_leftLayout.setVerticalGroup(
            panel_leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_leftLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_fast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(176, Short.MAX_VALUE))
        );

        add(panel_left, java.awt.BorderLayout.WEST);

        panel_choose.setBorder(javax.swing.BorderFactory.createTitledBorder("Choose timer"));

        rad_count.setSelected(true);
        rad_count.setText("countdown");

        rad_clock.setText("clock/date");

        javax.swing.GroupLayout panel_chooseLayout = new javax.swing.GroupLayout(panel_choose);
        panel_choose.setLayout(panel_chooseLayout);
        panel_chooseLayout.setHorizontalGroup(
            panel_chooseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_chooseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_chooseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rad_count)
                    .addComponent(rad_clock))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        panel_chooseLayout.setVerticalGroup(
            panel_chooseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_chooseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rad_count)
                .addGap(18, 18, 18)
                .addComponent(rad_clock)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_timer.setLayout(new java.awt.CardLayout());

        panel_timer_countdown.setBorder(javax.swing.BorderFactory.createTitledBorder("Countdown"));

        jLabel3.setText("HH");

        jLabel4.setText("SS");

        jLabel5.setText("MM");

        javax.swing.GroupLayout panel_timer_countdownLayout = new javax.swing.GroupLayout(panel_timer_countdown);
        panel_timer_countdown.setLayout(panel_timer_countdownLayout);
        panel_timer_countdownLayout.setHorizontalGroup(
            panel_timer_countdownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_timer_countdownLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_timer_countdownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSpinner_count_h, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_timer_countdownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_timer_countdownLayout.createSequentialGroup()
                        .addComponent(jSpinner_count_m, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinner_count_s, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_timer_countdownLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        panel_timer_countdownLayout.setVerticalGroup(
            panel_timer_countdownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_timer_countdownLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(panel_timer_countdownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_timer_countdownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinner_count_h, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner_count_m, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner_count_s, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        panel_timer.add(panel_timer_countdown, "card_count");

        panel_timer_clock.setBorder(javax.swing.BorderFactory.createTitledBorder("date/time"));

        jLabel1.setText("Time");

        jLabel2.setText("Date");

        DateFormat df = new SimpleDateFormat("d/M/yyyy");
        JSpinner.DateEditor editor = new JSpinner.DateEditor(jSpinner_date, "dd MMM yyyy");
        jSpinner_date.setEditor(editor);

        SpinnerDateModel model2=new SpinnerDateModel(now, null, null, Calendar.DAY_OF_WEEK);
        jSpinner_time = new javax.swing.JSpinner(model2);
        JSpinner.DateEditor editor2 = new JSpinner.DateEditor(jSpinner_time, "HH:mm:ss");
        jSpinner_time.setEditor(editor2);

        javax.swing.GroupLayout panel_timer_clockLayout = new javax.swing.GroupLayout(panel_timer_clock);
        panel_timer_clock.setLayout(panel_timer_clockLayout);
        panel_timer_clockLayout.setHorizontalGroup(
            panel_timer_clockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_timer_clockLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_timer_clockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSpinner_date)
                    .addComponent(jSpinner_time))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_timer_clockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addContainerGap(176, Short.MAX_VALUE))
        );
        panel_timer_clockLayout.setVerticalGroup(
            panel_timer_clockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_timer_clockLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_timer_clockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinner_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(panel_timer_clockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jSpinner_time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        panel_timer.add(panel_timer_clock, "card_clock");

        panel_options.setBorder(javax.swing.BorderFactory.createTitledBorder("Options"));

        rad_pow.setSelected(true);
        rad_pow.setText("Power OFf");
        rad_pow.setName("poweroff"); // NOI18N

        rad_rest.setText("Restart");
        rad_rest.setName("restart"); // NOI18N

        rad_sleep.setText("Sleep");
        rad_sleep.setName("sleep"); // NOI18N
        rad_sleep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad_sleepActionPerformed(evt);
            }
        });

        rad_lock.setText("Lock");
        rad_lock.setName("sleep"); // NOI18N
        rad_lock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad_lockActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_optionsLayout = new javax.swing.GroupLayout(panel_options);
        panel_options.setLayout(panel_optionsLayout);
        panel_optionsLayout.setHorizontalGroup(
            panel_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_optionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_optionsLayout.createSequentialGroup()
                        .addGroup(panel_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(rad_pow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rad_rest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rad_sleep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(rad_lock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panel_optionsLayout.setVerticalGroup(
            panel_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_optionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rad_pow)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rad_rest)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rad_sleep)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rad_lock)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        button_run.setText("RUN");

        button_cancel.setText("CANCEL");

        javax.swing.GroupLayout panel_centerLayout = new javax.swing.GroupLayout(panel_center);
        panel_center.setLayout(panel_centerLayout);
        panel_centerLayout.setHorizontalGroup(
            panel_centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_centerLayout.createSequentialGroup()
                .addGroup(panel_centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_centerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panel_centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(panel_options, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panel_centerLayout.createSequentialGroup()
                                .addComponent(panel_choose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(panel_timer, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panel_centerLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(button_run, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(button_cancel)))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        panel_centerLayout.setVerticalGroup(
            panel_centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_centerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel_timer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_choose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(panel_options, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(panel_centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_run, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        add(panel_center, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout panel_bottomLayout = new javax.swing.GroupLayout(panel_bottom);
        panel_bottom.setLayout(panel_bottomLayout);
        panel_bottomLayout.setHorizontalGroup(
            panel_bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
        panel_bottomLayout.setVerticalGroup(
            panel_bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );

        add(panel_bottom, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void rad_sleepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad_sleepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rad_sleepActionPerformed

    private void rad_lockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad_lockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rad_lockActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.ButtonGroup buttonGroup_choose;
    public javax.swing.ButtonGroup buttonGroup_options;
    public javax.swing.JButton button_cancel;
    public javax.swing.JButton button_run;
    private javax.swing.JLabel fast_1;
    private javax.swing.JLabel fast_10;
    private javax.swing.JLabel fast_2;
    private javax.swing.JLabel fast_20;
    private javax.swing.JLabel fast_3;
    private javax.swing.JLabel fast_30;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSpinner jSpinner_count_h;
    private javax.swing.JSpinner jSpinner_count_m;
    private javax.swing.JSpinner jSpinner_count_s;
    private javax.swing.JSpinner jSpinner_date;
    public javax.swing.JSpinner jSpinner_time;
    private javax.swing.JLabel label_title;
    private javax.swing.JPanel panel_bottom;
    private javax.swing.JPanel panel_center;
    private javax.swing.JPanel panel_choose;
    private javax.swing.JPanel panel_fast;
    private javax.swing.JPanel panel_left;
    private javax.swing.JPanel panel_options;
    public javax.swing.JPanel panel_timer;
    private javax.swing.JPanel panel_timer_clock;
    private javax.swing.JPanel panel_timer_countdown;
    private javax.swing.JPanel panel_title;
    public javax.swing.JRadioButton rad_clock;
    public javax.swing.JRadioButton rad_count;
    public javax.swing.JRadioButton rad_lock;
    public javax.swing.JRadioButton rad_pow;
    public javax.swing.JRadioButton rad_rest;
    public javax.swing.JRadioButton rad_sleep;
    private javax.swing.JLabel title_fast;
    // End of variables declaration//GEN-END:variables
}
